### PR TITLE
Add soapy sdr devices support

### PR DESCRIPTION
**Pull request by fcrohas**
Simple support for Soapy API to allow more devices and also remote devices.

### CODE REVIEW

**Comment by fcrohas** [comment]
I still have a bug in the code the reception is not as good as the native implementation. I m looking at it.

**Comment by szpajder** [comment]
Thanks Fabrice, looks good at first glance (I'm yet to test this).

Two comments:

- Don't tokenize parameter strings manually (and leak memory while doing it), there is an API for that - `SoapySDRKwargs_fromString`. An example of its usage is in https://github.com/szpajder/RTLSDR-Airband/blob/master/input-soapysdr.cpp .

- "Pluto, BladeRF, Airspy, HackRF and much more" - have you actually verified that it works correctly on these devices? Because I'm not into answering support calls saying "docs told me that it works with my receiver, but it fails miserably". All the rados have their pecularities. I guess it won't work on Airspies, because they don't support a sample rate of 2100000 sps (nor arbitrary sample rates in general - see https://github.com/szpajder/RTLSDR-Airband/issues/60#issuecomment-355622103 and followups). So please make a clear "tested on:" statement and list the equipment which you have confirmed the program to work with.

**Comment by fcrohas** [comment]
OK i understand. I checked airspy source code before my pull request and does not see any issue.
Anyway i removed my comment and replaced it with tested devices as i did not receive my other device before a long time.

Nice to see that soapy is also added to rtlsdr-airband

**Comment by szpajder** [comment]
I was about to merge your request, but you deleted it?

What's the idea behind this?

**Comment by fcrohas** [comment]
Hi,

  The code was really bad, there was bug with ring_index ... wrongly counted. And i discover that soapy readstream does not send back the requested buffer size.. but often smaller size, so the ring buffer was not well handled. I just fixed it and i m doing some more test. It look better now

**Comment by fcrohas** [comment]
Ok i think i fixed the buffer think, Soapy version run for 24 hours and it is working quite good now.
See my EleasticSearch datas.
sdrplay with soapy

**Comment by szpajder** [comment]
Merged, thanks!

**Pull request merged**
